# render.yaml
services:
  - type: web
    name: zynexranking
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.ts
    plan: free

    # Để Render biết dùng TypeScript
    envVars:
      NODE_VERSION: ~20
